### PR TITLE
[issues/161] Comment function not allowed Java (9,10) > 8

### PR DESCRIPTION
**Pull request by lberoiza**
Possible Solution to Issue #161

### CODE REVIEW

**Comment by kares** [comment]
sorry, but this isn't a solution really - Java only prints you with the first warning.
after this you might likely be getting more + as CI suggest not setting the ctor accessible breaks stuff!

**Comment by lberoiza** [comment]
Hi,

Do you have a suggestion, how we can solve this issue, I don't really understand what you mean. 
Regards
Luis

**Comment by mkristian** [comment]
@lberoiza not setting `constructor.setAccessible(true);` breaks functionality (see travis-ci ). so unless we find a way to retain functionality and remove the warning we probably stick with the warning.

**Comment by kares** [comment]
hmm so this is going in a way of silencing the JDK internal logger **reflectively** :)
very much appreciate all the effort ... but not sure we would want code such as these around.
it doesn't really solve the issue + we would probably need a fork treating unsafe as JRuby does etc.
long term solution would be to rewrite most of these to use light-weight BC APIs and do not rely on JDK APIs

**Comment by kares** [comment]
we've attempted to reduce the reflection performed by security helper (for 0.10.5), if this turns out problematic we should attempt some silencing but generally we do not want to have "ugly" module workarounds. thanks for your code thought, very interesting that people actually use these hacks.

**Pull request closed without merging**
