### PR TITLE
Add cipher suite strings for IBM JRE

### PR DESCRIPTION
**Pull request by ysohda**
Add cipher suite strings for IBM JRE into SuiteToOSSL mapping

### CODE REVIEW

**Comment by kares** [comment]
Thanks Yuki, this is excellent ... if you have a change could you update the comment with a note from #125 

from :
```
/* For IBM JRE */
```
to something like :
```
/* For IBM JRE: suite names start with "SSL_". On Oracle JRE, the suite names start with "TLS_" */
```

**Comment by ysohda** [comment]
Hi Kares,

Thank you for your review.
I updated the comment and also made EDCH/EDCHE SHA384 cipher suites available not only for IBM JRE but also for Oracle JRE.
Btw, about AES GCM ciper cuites introduced in Java 8, I added mapping entries for IBM JRE. So if AES GCM cipher suites are available on jruby-openssl, they will be also available on IBM JRE.

Thank you,
Yuki.

**Comment by ysohda** [comment]
Hi @kares ,

Can I have any update?
It would be nice that the fix is included in the next JRuby-Openssl and JRuby releases (0.9.21 & 9.1.9).

Thank you,
Yuki.

**Comment by kares** [comment]
Sure will be in next jossl release. Not sure if it will make it into 9.1.9 (its a lot of boilerplate to test a release).
But you'll be able to `gem update` later and we can push you a dev SNAPSHOT if that is usable for you ...

**Comment by kares** [comment]
https://oss.sonatype.org/content/repositories/snapshots/rubygems/jruby-openssl/0.9.21.dev-SNAPSHOT/

**Comment by ysohda** [comment]
Hi Kares,

Thank you for creating a snapshot. I'm going to use it.
May I have an approximate next release date if it is planned?

Thank you,
Yuki.

**Pull request merged**
